FROM debian:9-slim

RUN apt-get update; \
	apt-get install -y --no-install-recommends \
		python-flask \
		&& \
		rm -rf /var/lib/apt/lists/*

COPY src/app.py /app/src/
WORKDIR /app/src/

EXPOSE 808


CMD ["python", "app.py"]
