FROM python:3.6-alpine

COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY src/app.py /app/src/
WORKDIR /app/src/

EXPOSE 8080

ARG VER=latest
RUN echo $VER > /app/src/version

CMD ["python", "app.py"]
