apiVersion: v1
kind: Pod
metadata:
  name: fussy-liveness-test
spec:
  containers:
  - image: cloudowski/fussy-container:0.1
    name: fussy
    livenessProbe:
      exec:
        command:
        - test
        - -f
        - /tmp/healthy
      initialDelaySeconds: 15
      periodSeconds: 5
