apiVersion: v1
kind: Pod
metadata:
  name: testvol
spec:
  containers:
  - image: cloudowski/fussy-container
    name: test-container
    volumeMounts:
    - mountPath: /datavol
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /data
