apiVersion: v1
kind: Pod
metadata:
  name: podvol-pvc1
spec:
  containers:
  - image: cloudowski/fussy-container
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: mystorage
  volumes:
  - name: mystorage
    persistentVolumeClaim:
      claimName: pvc-host1
