apiVersion: apps/v1
kind: Deployment
metadata:
  name: cow-update

  labels:
    app: cow

spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  selector:
    matchLabels:
      app: cow
      herd: green
  template:
    metadata:
      labels:
        app: cow
        herd: green
    spec:
      # terminationGracePeriodSeconds: 5

      containers:
        - image: cloudowski/krazy-cow:latest
          # imagePullPolicy: Always
          name: cow

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
            failureThreshold: 2

          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https

          env:
            - name: KC_LOGGING_LEVEL
              value: "DEBUG"
