apiVersion: v1
kind: Pod
metadata:
  name: cow-https-auth
spec:
  containers:
    - image: cloudowski/krazy-cow:latest
      name: cow
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 20
        periodSeconds: 5
      env:
        - name: KC_HTTP_TLS_ENABLED
          value: "true"
        - name: KC_HTTP_TLS_CERT
          value: "/tls/tls.crt"
        - name: KC_HTTP_TLS_KEY
          value: "/tls/tls.key"
        - name: KC_HTTP_AUTH_ENABLED
          value: "true"
        - name: KC_HTTP_AUTH_CREDENTIALS
          value: "/auth/credentials.txt"
      volumeMounts:
        - name: cow-tls
          mountPath: /tls/
        - name: cow-auth
          mountPath: /auth/

  volumes:
    - name: cow-tls
      secret:
        secretName: cow-tls
    - name: cow-auth
      secret:
        secretName: cow-auth
