apiVersion: v1
kind: Pod
metadata:
  name: cow-https
spec:
  containers:
    - image: cloudowski/krazy-cow:latest
      name: cow
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 20
        periodSeconds: 5
        # quickfix
        timeoutSeconds: 5
      env:
        - name: KC_HTTP_TLS_ENABLED
          value: "true"
        - name: KC_HTTP_TLS_CERT
          value: "/tls/tls.crt"
        - name: KC_HTTP_TLS_KEY
          value: "/tls/tls.key"
      volumeMounts:
        - name: cow-tls
          mountPath: /tls/

  volumes:
    - name: cow-tls
      secret:
        secretName: cow-tls
