apiVersion: v1
kind: Pod
metadata:
  name: cow1
  labels:
    app: cow
spec:
  containers:
    - name: cow
      image: cloudowski/krazy-cow
      ports:
        - containerPort: 8080
          name: http
