apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-rocketchat
  labels:
    jenkins-jenkins-config: "true"
data:
  jenkins.yaml: |+
    unclassified:
        rocketChatNotifier:
            buildServerUrl: "/"
            channel: "cicd"
            username: "jenkins"
            password: "J3nk1ns"
            rocketServerUrl: "https://chat.app.labs.k8sworkshops.com/"
            trustSSL: false
