---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol1
spec:
  storageClassName: "green-and-big"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.100.100
    path: "/vol1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol2
spec:
  storageClassName: "green-and-big"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.100.100
    path: "/vol2"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsvol3
spec:
  storageClassName: "green-and-big"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.100.100
    path: "/vol3"
