apiVersion: v1
kind: Service
metadata:
  name: ngingxsvc
  labels:
    tier: frontend
spec:
  ports:
  - port: 80
    nodePort: 30180
    protocol: TCP
  selector:
    tier: frontend
  type: NodePort
