apiVersion: v1
kind: Pod
metadata:
  name: counter2
spec:
  containers:
  - name: count
    image: ubuntu:16.04
    args: [bash, -c,
           'for ((i = 0; ; i++)); do echo "$i: $(date)"; sleep 1; done']
    resources:
      limits:
        memory: 200Mi
      requests:
        cpu: 2200m
        memory: 200Mi
