apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  selector:
    matchLabels:
      app: flaskdemo
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskdemo
        version: v1
    spec:
      containers:
        - name: flaskdemo
          image: cloudowski/flaskdemo:0.1
