apiVersion: v1
kind: Pod
metadata:
  name: cow-env-configure
spec:
  containers:
    - image: cloudowski/krazy-cow:latest
      name: cow
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
        initialDelaySeconds: 20
        periodSeconds: 5
      env:
        - name: KC_LOGGING_LEVEL
          value: "DEBUG"
