apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  # change if your minikube/kubernetes cluster has different IP address service pool
  clusterIP: 10.96.100.100
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
