apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: shoppinglists.cloudowski.com
spec:
  group: cloudowski.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: shoppinglists
    singular: shoppinglist
    kind: ShoppingList
    shortNames:
      - sl
