apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
data:
  jenkins.yaml: |+
    credentials:
      system:
        domainCredentials:
          - credentials:
              - usernamePassword:
                  scope:    GLOBAL
                  id:       dockerhub
                  username: root
                  password: toor
