apiVersion: v1
kind: Pod
metadata:
  namespace: 
  name: secretdemo
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - sh
    - -c
    - while true; do sleep 3600; done
    volumeMounts:
    - name: my-password
      mountPath: /data
    env:
      - name: SECRET_USER
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: myuser
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: mypassword
  volumes:
  - name: my-password
    secret:
      secretName: my-secret-password
